### ISSUE TITLE
daysToExpire

### ISSUE THREAD

**Issue by cyberlahy** [AhmedAbogameel/media_cache_manager#3]
Hi,
Is daysToExpire resets when a media is opened?
I want that media frequently used never expires but always reset for new daysToExpire.

Thanks

**Comment by AhmedAbogameel** [comment]
Hello,
I am investigating this bug,
daysToExpire should not reset every time.
i will deploy a hotfix version if bug exists.
Thanks for information.

**Comment by cyberlahy** [comment]
No,
I want that if I make daysToExpire to 10 and if the user load again the image the daysToExpire should reset for a new 10 days,
so frequently opened media never expire

**Comment by AhmedAbogameel** [comment]
Oh got it.
it's a pretty idea,
it wants some massive effort,
but i am working on something similar that helps me achieving this pretty idea.

If you have any ideas or inquiries, do not hesitate, my friend.
