### ISSUE TITLE
File not downloading after being removed from the cache!

### ISSUE THREAD

**Issue by TheUnknownCorp** [AhmedAbogameel/media_cache_manager#7]
Hello there, 

I am using **media_cache_manager: ^0.2.2.** Everything is working perfectly fine, the file loads initially, caches, and then removes at the desired time. But there is an issue, when the file is removed from the cache, instead of downloading it again, it throws this error: 

`The following PathNotFoundException was thrown resolving an image codec:
Cannot retrieve length of file, path = '/data/user/0/com.example.example/cache/549679bf60464fc19e9d1c02fa75eb1b.webp' (OS Error: No such file or directory, errno = 2)
`

Furthermore, I tried it on the IOS Simulator and the Android real device. If I delete the complete data of my app from the device settings, the file is downloaded again. But if I delete only the cache, it doesn't download the image again. It throws the error mentioned above!

**Comment by AhmedAbogameel** [comment]
thanks for sharing 
i have solved it in version 0.3.0
