### ISSUE TITLE
Local files encryption 

### ISSUE THREAD

**Issue by pigivc** [AhmedAbogameel/media_cache_manager#9]
First of all thank you for providing such a helpful package.

For my project i need to encrypt local files. Just wanted to know if it's possible. For example we give download url lile file:///...

Regards

**Comment by AhmedAbogameel** [comment]
Thanks for your support @pigivc 
Do you want to encrypt local files from device then give you the encrypted file path ?

**Comment by pigivc** [comment]
> Thanks for your support @pigivc Do you want to encrypt local files from device then give you the encrypted file path ?

Thanks for reply, Back then it was a desired feature.  Now the need for such feature no longer needed
